// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOIhIpPw72lBB95QQFXK9mAKiNdHm_mUo',
    appId: '1:560481521115:web:55ff50d79ae1c75e486bfe',
    messagingSenderId: '560481521115',
    projectId: 'fir-all-auth-52e4f',
    authDomain: 'fir-all-auth-52e4f.firebaseapp.com',
    storageBucket: 'fir-all-auth-52e4f.appspot.com',
    measurementId: 'G-2P3T5T2B2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoJO2QffKeXYcnCsvQW4FFVGZl5EHX_is',
    appId: '1:560481521115:android:c950a583ef7b97ab486bfe',
    messagingSenderId: '560481521115',
    projectId: 'fir-all-auth-52e4f',
    storageBucket: 'fir-all-auth-52e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlItK8PUepD7UCjXOxfVidJqZDxY0nL9k',
    appId: '1:560481521115:ios:f16d5e1c177b7d82486bfe',
    messagingSenderId: '560481521115',
    projectId: 'fir-all-auth-52e4f',
    storageBucket: 'fir-all-auth-52e4f.appspot.com',
    androidClientId: '560481521115-8uqjhvv8cmrnhqdn4g5ptl318vbq8a68.apps.googleusercontent.com',
    iosClientId: '560481521115-gd8jp1jtnsgo0qnhdv9vsgo1iob8vbof.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthAllFeature',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlItK8PUepD7UCjXOxfVidJqZDxY0nL9k',
    appId: '1:560481521115:ios:85d63a9adde93a83486bfe',
    messagingSenderId: '560481521115',
    projectId: 'fir-all-auth-52e4f',
    storageBucket: 'fir-all-auth-52e4f.appspot.com',
    androidClientId: '560481521115-8uqjhvv8cmrnhqdn4g5ptl318vbq8a68.apps.googleusercontent.com',
    iosClientId: '560481521115-t61sulu3rem8kl7752gm4c0n65iaftnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthAllFeature.RunnerTests',
  );
}
